Update esercizi

diff --git a/esercizi b/esercizi
--- a/esercizi
+++ b/esercizi
@@ -73,3 +73,31 @@ while (( $J > 0 )) ; do
 echo ${!J}
 (( J=$J-1 ))
 done
+
+echo -e "ciao\n"
+
+echo -n "ciao"
+
+ls
+
+script:
+for f in * ; do
+echo "file is $f"
+ls -ld $f
+done 
+
+script:
+for f in * ; do echo "file is $f" ; ls -ld $f ; done ; if (( $? != 0 )) ; then echo "errore" ; fi ; done
+
+#!/bin/bash
+
+FILES=$(ls)
+
+for file1 in $FILES ; do
+for file2 in $FILES ; do
+for file3 in $FILES ; do
+echo "($file1;$file2;file3)"
+done
+done 
+done
+
